# Generated by Django 2.2.6 on 2020-04-03 09:58

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('location', models.CharField(blank=True, max_length=250)),
                ('website', models.URLField(blank=True, default='')),
                ('mobile', models.BigIntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
                ('verified', models.BooleanField(default=False)),
                ('oneSignalId', models.CharField(blank=True, default='', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
